export const ApiEndpoints = {
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  AUTH_LOGOUT: '/auth/logout',
  AUTH_ME: '/auth/me',
  AUTH_PROFILE: '/auth/profile',
  AUTH_FORGOT_PASSWORD: '/auth/forgot-password',
  USERS_PROFILE: '/users/profile',
  USERS: '/users',
  USERS_BY_ID: '/users',
  UPDATE_USER: '/users',
  BLACKLIST: '/users',
  RESTORE: '/users',
  VEHICLES_SELLING: '/vehicles/selling-vehicles',
  VEHICLES_BY_ID: '/vehicles',
  VEHICLE_EDIT: '/vehicles',
  VEHICLE_DELETE: '/vehicles',
  VEHICLE_RESTORE: '/vehicles',
  INSPECTION_VEHICLES: '/inspections/vehicles',
  INSPECTION_VEHICLE_BY_ID: '/inspections/vehicles',
  ASSIGN_INSPECTOR: '/inspections/assign',
  UPDATE_INSPECTION: '/inspections',
  UPDATE_AUCTION: '/auctions',
  AUCTIONS: '/auctions',
  SELECT_WINNER: '/auctions/:auctionId/vehicles/:vehicleId/select-winner',
  END_AUCTION: '/auctions/:auctionId/end',
  REGISTER_VEHICLE_ACCESS: '/auctions/:auctionId/vehicles/:vehicleId/register-access',
  VEHICLE_ACCESS_STATUS: '/auctions/:auctionId/vehicles/:vehicleId/access-status',
  ADD_VEHICLE_TO_AUCTION: '/auctions/:auctionId/vehicles',
  REMOVE_VEHICLE_FROM_AUCTION: '/auctions/:auctionId/vehicles/:vehicleId',
} as const;

export type ApiEndpoints = typeof ApiEndpoints[keyof typeof ApiEndpoints];
